services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: vnest
      POSTGRES_PASSWORD: vnest
      POSTGRES_DB: incubation-backend
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure

volumes:
  pg_data:

